-- S�lectionner la base de donn�es 'gedcocanne'
USE DB_GESPONT_FK;
GO

-- Suppression de la table F_PREMPESEE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'F_PREMPESEE')
BEGIN
    DROP TABLE F_PREMPESEE;
END
GO

-- Suppression de la table F_PESEE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'F_PESEE')
BEGIN
    DROP TABLE F_PESEE;
END
GO



-- Suppression de la table F_PESEE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'F_TYPECANNE')
BEGIN
    DROP TABLE F_TYPECANNE;
END
GO
