-- S�lectionner la base de donn�es 'gedcocanne'
USE gedcocanne;
GO

-- Suppression de la table F_PREMPESEE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'F_PREMPESEE')
BEGIN
    DROP TABLE F_PREMPESEE;
END
GO

-- Suppression de la table F_PESEE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'F_PESEE')
BEGIN
    DROP TABLE F_PESEE;
END
GO


-- Suppression de la table DECHARGERTABLE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DECHARGERTABLE')
BEGIN
    DROP TABLE DECHARGERTABLE;
END
GO

-- Suppression de la table DECHARGERCOURS
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DECHARGERCOURS')
BEGIN
    DROP TABLE DECHARGERCOURS;
END
GO

-- Suppression de la table TABLECANNE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TABLECANNE')
BEGIN
    DROP TABLE TABLECANNE;
END
GO

-- Suppression de la table TAS
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TAS')
BEGIN
    DROP TABLE TAS;
END
GO

-- Suppression de la table LIGNE
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LIGNE')
BEGIN
    DROP TABLE LIGNE;
END
GO

-- Suppression de la table AGENT
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AGENT')
BEGIN
    DROP TABLE AGENT;
END
GO
